name:learn
run-name: ${{ github.actor }} Actions
on: [push]
jobs:
  check-bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      with:
        node-verion: '14'
      - run: npm install -g bats
      - run: bats -v